spring.application.name=messager

spring.config.import=optional:file:.env[.properties]


spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/solaria_messenger_db?uuidRepresentation=standard}
spring.mongodb.database=solaria_messenger_db
spring.data.mongodb.auto-index-creation=true

spring.mongodb.representation.uuid=standard

spring.web.error.include-message=never
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false
spring.web.error.include-binding-errors=never

app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

app.jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}
app.jwt.issuer=solaria-auth

# Observabilidade (Actuator + Micrometer + Micrometer Tracing + OpenTelemetry SDK)
# aplicacao exporta OTLP para o Collector 

# identidade da aplicação no backend de observabilidade
management.opentelemetry.resource-attributes.service.name=${spring.application.name}
management.opentelemetry.resource-attributes.service.version=${SERVICE_VERSION:dev}
management.opentelemetry.resource-attributes.deployment.environment=${DEPLOYMENT_ENVIRONMENT:local}

# endpoints OTLP (apontam para o collector)
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/logs

# % de traces enviados | padrão de 100% porque collector decide se envia ou descarta trace
management.tracing.sampling.probability=${OTEL_TRACES_SAMPLING_PROBABILITY:1.0}

# restringindo actuactor para /health e /info 
management.endpoints.web.exposure.include=health,info
management.endpoints.access.default=none
management.endpoint.health.access=read-only
management.endpoint.info.access=read-only

# integração com probres do k8s no Actuator ( /actuator/health/[liveness|readiness] )
management.endpoint.health.probes.enabled=true

# Verifica a saúde interna do Spring -> Se falhar o K8s reinicia o container
management.endpoint.health.group.liveness.include=livenessState

# Verifica o Spring + Banco de Dados -> Se falhar o K8s remove o pod do load balancer sem reiniciar
# o health contributor do Spring Data Mongo se chama 'mongo' 
management.endpoint.health.group.readiness.include=readinessState,mongo

# Oculta detalhes na resposta do /health (segurança+performance)
management.endpoint.health.show-details=never
management.endpoint.health.show-components=never
management.health.redis.enabled=false

# Habilita histogramas para calcular percentis (p50, p95, p99) no Grafana
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# medição de faixas de tempo para analise de distribuição de requests por tempo de latência no grafana
management.metrics.distribution.slo.http.server.requests=50ms,100ms,200ms,300ms,500ms,1s,2s,5s

# Valor mínimo considerado pelo histograma
management.metrics.distribution.minimum-expected-value.http.server.requests=5ms
# Valor máximo considerado pelo histograma
management.metrics.distribution.maximum-expected-value.http.server.requests=10s

# conteudo do endpoint /actuator/info
management.info.env.enabled=false
management.info.java.enabled=true
management.info.os.enabled=true
