spring.application.name=messager

spring.config.import=optional:file:.env[.properties]


spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/solaria_messenger_db?uuidRepresentation=standard}
spring.mongodb.database=solaria_messenger_db
spring.data.mongodb.auto-index-creation=true

spring.mongodb.representation.uuid=standard

spring.web.error.include-message=never
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false
spring.web.error.include-binding-errors=never

app.cors.allowed-origins=http://localhost:3000,http://localhost:5173

app.jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}
app.jwt.issuer=solaria-auth
